# Generated by Django 5.0.7 on 2024-08-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canva_app', '0003_women_womencart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='product_name',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='product_price',
            new_name='productprice',
        ),
    ]
