# Generated by Django 5.0.7 on 2024-08-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canva_app', '0004_rename_product_name_women_productname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='women',
            table='Ladies',
        ),
    ]
