# Generated by Django 5.0.7 on 2024-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canva_app', '0008_rename_endsale_endsalecart_lid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endsalecart',
            old_name='lid',
            new_name='endsale',
        ),
    ]
