# Generated by Django 5.0.7 on 2024-08-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canva_app', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
